@baseUrl = http://localhost:5000

# メッセージ送信のテスト
POST {{baseUrl}}/api/messages/send
Content-Type: application/json

{
  "message": "おはようございます"
}

###
POST {{baseUrl}}/api/messages/send
Content-Type: application/json

{
  "message": "お疲れ様です"
}

###
#メッセージ取得（全件取得）のテスト
GET {{baseUrl}}/api/messages

